export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_EXPERIMENTS_START = 'FETCH_EXPERIMENTS_START';
export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';

export const SET_EXPERIMENTS = 'SET_EXPERIMENTS';
export const LOAD_EXPERIMENTS = 'LOAD_EXPERIMENTS';
export const FETCH_EXPERIMENTS_SUCCESS = 'FETCH_EXPERIMENTS_SUCCESS';
export const FETCH_EXPERIMENTS_FAIL = 'FETCH_EXPERIMENTS_FAIL';

export const CREATE_EXPERIMENTS_START = 'CREATE_EXPERIMENTS_START';
export const CREATE_EXPERIMENTS_SUCCESS = 'CREATE_EXPERIMENTS_SUCCESS';
export const CREATE_EXPERIMENTS_FAIL = 'CREATE_EXPERIMENTS_FAIL';

export const CREATE_ARTICLE_START = 'CREATE_ARTICLE_START';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';

export const FETCH_ARTICLE_START = 'FETCH_ARTICLE_START';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const SET_ARTICLE = 'SET_ARTICLE';
export const LOAD_ARTICLE = 'LOAD_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';

export const GRAPH_UPDATED = 'GRAPH_UPDATED';
export const INIT_CY = 'INIT_CY';

export const UPDATE_MATRIX = 'UPDATE_MATRIX';
export const INIT_MATRIX = 'INIT_MATRIX';

export const UPDATE_CELL = 'UPDATE_CELL';
